//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EveOPreview.View.Implementation {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MainForm {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainForm() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EveOPreview.View.Implementation.MainForm", typeof(MainForm).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似于 False 的 System.Boolean 类型的本地化资源。
        /// </summary>
        public static bool AboutPanel_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("AboutPanel.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 True 的 System.Boolean 类型的本地化资源。
        /// </summary>
        public static bool AboutPanel_Locked {
            get {
                object obj = ResourceManager.GetObject("AboutPanel.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 False 的 System.Boolean 类型的本地化资源。
        /// </summary>
        public static bool AboutTabPage_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("AboutTabPage.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 True 的 System.Boolean 类型的本地化资源。
        /// </summary>
        public static bool AboutTabPage_Locked {
            get {
                object obj = ResourceManager.GetObject("AboutTabPage.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 True 的 System.Boolean 类型的本地化资源。
        /// </summary>
        public static bool ActiveClientHighlightColorButton_Locked {
            get {
                object obj = ResourceManager.GetObject("ActiveClientHighlightColorButton.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 False 的 System.Boolean 类型的本地化资源。
        /// </summary>
        public static bool ClientsPanel_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("ClientsPanel.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 True 的 System.Boolean 类型的本地化资源。
        /// </summary>
        public static bool ClientsPanel_Locked {
            get {
                object obj = ResourceManager.GetObject("ClientsPanel.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 False 的 System.Boolean 类型的本地化资源。
        /// </summary>
        public static bool ClientsTabPage_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("ClientsTabPage.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 True 的 System.Boolean 类型的本地化资源。
        /// </summary>
        public static bool ClientsTabPage_Locked {
            get {
                object obj = ResourceManager.GetObject("ClientsTabPage.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 False 的 System.Boolean 类型的本地化资源。
        /// </summary>
        public static bool ContentTabControl_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("ContentTabControl.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 True 的 System.Boolean 类型的本地化资源。
        /// </summary>
        public static bool ContentTabControl_Locked {
            get {
                object obj = ResourceManager.GetObject("ContentTabControl.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 False 的 System.Boolean 类型的本地化资源。
        /// </summary>
        public static bool CreditMaintLabel_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("CreditMaintLabel.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 True 的 System.Boolean 类型的本地化资源。
        /// </summary>
        public static bool CreditMaintLabel_Locked {
            get {
                object obj = ResourceManager.GetObject("CreditMaintLabel.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 False 的 System.Boolean 类型的本地化资源。
        /// </summary>
        public static bool DescriptionLabel_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("DescriptionLabel.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 True 的 System.Boolean 类型的本地化资源。
        /// </summary>
        public static bool DescriptionLabel_Locked {
            get {
                object obj = ResourceManager.GetObject("DescriptionLabel.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 True 的 System.Boolean 类型的本地化资源。
        /// </summary>
        public static bool DocumentationLink_Locked {
            get {
                object obj = ResourceManager.GetObject("DocumentationLink.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 False 的 System.Boolean 类型的本地化资源。
        /// </summary>
        public static bool DocumentationLinkLabel_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("DocumentationLinkLabel.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 True 的 System.Boolean 类型的本地化资源。
        /// </summary>
        public static bool DocumentationLinkLabel_Locked {
            get {
                object obj = ResourceManager.GetObject("DocumentationLinkLabel.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 True 的 System.Boolean 类型的本地化资源。
        /// </summary>
        public static bool EnableActiveClientHighlightCheckBox_Locked {
            get {
                object obj = ResourceManager.GetObject("EnableActiveClientHighlightCheckBox.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 True 的 System.Boolean 类型的本地化资源。
        /// </summary>
        public static bool EnableClientLayoutTrackingCheckBox_Locked {
            get {
                object obj = ResourceManager.GetObject("EnableClientLayoutTrackingCheckBox.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 True 的 System.Boolean 类型的本地化资源。
        /// </summary>
        public static bool EnablePerClientThumbnailsLayoutsCheckBox_Locked {
            get {
                object obj = ResourceManager.GetObject("EnablePerClientThumbnailsLayoutsCheckBox.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 True 的 System.Boolean 类型的本地化资源。
        /// </summary>
        public static bool EnableThumbnailZoomCheckBox_Locked {
            get {
                object obj = ResourceManager.GetObject("EnableThumbnailZoomCheckBox.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 False 的 System.Boolean 类型的本地化资源。
        /// </summary>
        public static bool ExitMenuItem_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("ExitMenuItem.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 False 的 System.Boolean 类型的本地化资源。
        /// </summary>
        public static bool GeneralSettingsPanel_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("GeneralSettingsPanel.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 True 的 System.Boolean 类型的本地化资源。
        /// </summary>
        public static bool GeneralSettingsPanel_Locked {
            get {
                object obj = ResourceManager.GetObject("GeneralSettingsPanel.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 False 的 System.Boolean 类型的本地化资源。
        /// </summary>
        public static bool GeneralTabPage_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("GeneralTabPage.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 True 的 System.Boolean 类型的本地化资源。
        /// </summary>
        public static bool GeneralTabPage_Locked {
            get {
                object obj = ResourceManager.GetObject("GeneralTabPage.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 False 的 System.Boolean 类型的本地化资源。
        /// </summary>
        public static bool HeigthLabel_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("HeigthLabel.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 True 的 System.Boolean 类型的本地化资源。
        /// </summary>
        public static bool HeigthLabel_Locked {
            get {
                object obj = ResourceManager.GetObject("HeigthLabel.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 True 的 System.Boolean 类型的本地化资源。
        /// </summary>
        public static bool HideActiveClientThumbnailCheckBox_Locked {
            get {
                object obj = ResourceManager.GetObject("HideActiveClientThumbnailCheckBox.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 True 的 System.Boolean 类型的本地化资源。
        /// </summary>
        public static bool HideThumbnailsOnLostFocusCheckBox_Locked {
            get {
                object obj = ResourceManager.GetObject("HideThumbnailsOnLostFocusCheckBox.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 True 的 System.Boolean 类型的本地化资源。
        /// </summary>
        public static bool HighlightColorLabel_Locked {
            get {
                object obj = ResourceManager.GetObject("HighlightColorLabel.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 True 的 System.Boolean 类型的本地化资源。
        /// </summary>
        public static bool MinimizeInactiveClientsCheckBox_Locked {
            get {
                object obj = ResourceManager.GetObject("MinimizeInactiveClientsCheckBox.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 True 的 System.Boolean 类型的本地化资源。
        /// </summary>
        public static bool MinimizeToTrayCheckBox_Locked {
            get {
                object obj = ResourceManager.GetObject("MinimizeToTrayCheckBox.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 False 的 System.Boolean 类型的本地化资源。
        /// </summary>
        public static bool NameLabel_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("NameLabel.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 True 的 System.Boolean 类型的本地化资源。
        /// </summary>
        public static bool NameLabel_Locked {
            get {
                object obj = ResourceManager.GetObject("NameLabel.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Icon NotifyIcon_Icon {
            get {
                object obj = ResourceManager.GetObject("NotifyIcon.Icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 {X=17,Y=17} 的 System.Drawing.Point 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Point NotifyIcon_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("NotifyIcon.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 False 的 System.Boolean 类型的本地化资源。
        /// </summary>
        public static bool OpacityLabel_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("OpacityLabel.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 True 的 System.Boolean 类型的本地化资源。
        /// </summary>
        public static bool OpacityLabel_Locked {
            get {
                object obj = ResourceManager.GetObject("OpacityLabel.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 False 的 System.Boolean 类型的本地化资源。
        /// </summary>
        public static bool OverlaySettingsPanel_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("OverlaySettingsPanel.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 True 的 System.Boolean 类型的本地化资源。
        /// </summary>
        public static bool OverlaySettingsPanel_Locked {
            get {
                object obj = ResourceManager.GetObject("OverlaySettingsPanel.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 False 的 System.Boolean 类型的本地化资源。
        /// </summary>
        public static bool OverlayTabPage_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("OverlayTabPage.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 True 的 System.Boolean 类型的本地化资源。
        /// </summary>
        public static bool OverlayTabPage_Locked {
            get {
                object obj = ResourceManager.GetObject("OverlayTabPage.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 False 的 System.Boolean 类型的本地化资源。
        /// </summary>
        public static bool RestoreWindowMenuItem_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("RestoreWindowMenuItem.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 False 的 System.Boolean 类型的本地化资源。
        /// </summary>
        public static bool SeparatorMenuItem_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("SeparatorMenuItem.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 True 的 System.Boolean 类型的本地化资源。
        /// </summary>
        public static bool ShowThumbnailFramesCheckBox_Locked {
            get {
                object obj = ResourceManager.GetObject("ShowThumbnailFramesCheckBox.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 True 的 System.Boolean 类型的本地化资源。
        /// </summary>
        public static bool ShowThumbnailOverlaysCheckBox_Locked {
            get {
                object obj = ResourceManager.GetObject("ShowThumbnailOverlaysCheckBox.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 True 的 System.Boolean 类型的本地化资源。
        /// </summary>
        public static bool ShowThumbnailsAlwaysOnTopCheckBox_Locked {
            get {
                object obj = ResourceManager.GetObject("ShowThumbnailsAlwaysOnTopCheckBox.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 True 的 System.Boolean 类型的本地化资源。
        /// </summary>
        public static bool ThumbnailOpacityTrackBar_Locked {
            get {
                object obj = ResourceManager.GetObject("ThumbnailOpacityTrackBar.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 False 的 System.Boolean 类型的本地化资源。
        /// </summary>
        public static bool ThumbnailSettingsPanel_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("ThumbnailSettingsPanel.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 True 的 System.Boolean 类型的本地化资源。
        /// </summary>
        public static bool ThumbnailSettingsPanel_Locked {
            get {
                object obj = ResourceManager.GetObject("ThumbnailSettingsPanel.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 True 的 System.Boolean 类型的本地化资源。
        /// </summary>
        public static bool ThumbnailsHeightNumericEdit_Locked {
            get {
                object obj = ResourceManager.GetObject("ThumbnailsHeightNumericEdit.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 True 的 System.Boolean 类型的本地化资源。
        /// </summary>
        public static bool ThumbnailsList_Locked {
            get {
                object obj = ResourceManager.GetObject("ThumbnailsList.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 False 的 System.Boolean 类型的本地化资源。
        /// </summary>
        public static bool ThumbnailsListLabel_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("ThumbnailsListLabel.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 True 的 System.Boolean 类型的本地化资源。
        /// </summary>
        public static bool ThumbnailsListLabel_Locked {
            get {
                object obj = ResourceManager.GetObject("ThumbnailsListLabel.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 True 的 System.Boolean 类型的本地化资源。
        /// </summary>
        public static bool ThumbnailsWidthNumericEdit_Locked {
            get {
                object obj = ResourceManager.GetObject("ThumbnailsWidthNumericEdit.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 False 的 System.Boolean 类型的本地化资源。
        /// </summary>
        public static bool ThumbnailTabPage_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("ThumbnailTabPage.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 True 的 System.Boolean 类型的本地化资源。
        /// </summary>
        public static bool ThumbnailTabPage_Locked {
            get {
                object obj = ResourceManager.GetObject("ThumbnailTabPage.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 True 的 System.Boolean 类型的本地化资源。
        /// </summary>
        public static bool ThumbnailZoomFactorNumericEdit_Locked {
            get {
                object obj = ResourceManager.GetObject("ThumbnailZoomFactorNumericEdit.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 False 的 System.Boolean 类型的本地化资源。
        /// </summary>
        public static bool TitleMenuItem_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("TitleMenuItem.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 {X=123,Y=17} 的 System.Drawing.Point 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Point TrayMenu_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("TrayMenu.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 False 的 System.Boolean 类型的本地化资源。
        /// </summary>
        public static bool WidthLabel_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("WidthLabel.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 True 的 System.Boolean 类型的本地化资源。
        /// </summary>
        public static bool WidthLabel_Locked {
            get {
                object obj = ResourceManager.GetObject("WidthLabel.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 True 的 System.Boolean 类型的本地化资源。
        /// </summary>
        public static bool ZoomAanchorCRadioButton_Locked {
            get {
                object obj = ResourceManager.GetObject("ZoomAanchorCRadioButton.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 True 的 System.Boolean 类型的本地化资源。
        /// </summary>
        public static bool ZoomAanchorERadioButton_Locked {
            get {
                object obj = ResourceManager.GetObject("ZoomAanchorERadioButton.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 True 的 System.Boolean 类型的本地化资源。
        /// </summary>
        public static bool ZoomAanchorNERadioButton_Locked {
            get {
                object obj = ResourceManager.GetObject("ZoomAanchorNERadioButton.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 True 的 System.Boolean 类型的本地化资源。
        /// </summary>
        public static bool ZoomAanchorNRadioButton_Locked {
            get {
                object obj = ResourceManager.GetObject("ZoomAanchorNRadioButton.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 True 的 System.Boolean 类型的本地化资源。
        /// </summary>
        public static bool ZoomAanchorNWRadioButton_Locked {
            get {
                object obj = ResourceManager.GetObject("ZoomAanchorNWRadioButton.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 True 的 System.Boolean 类型的本地化资源。
        /// </summary>
        public static bool ZoomAanchorSERadioButton_Locked {
            get {
                object obj = ResourceManager.GetObject("ZoomAanchorSERadioButton.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 True 的 System.Boolean 类型的本地化资源。
        /// </summary>
        public static bool ZoomAanchorSRadioButton_Locked {
            get {
                object obj = ResourceManager.GetObject("ZoomAanchorSRadioButton.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 True 的 System.Boolean 类型的本地化资源。
        /// </summary>
        public static bool ZoomAanchorSWRadioButton_Locked {
            get {
                object obj = ResourceManager.GetObject("ZoomAanchorSWRadioButton.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 True 的 System.Boolean 类型的本地化资源。
        /// </summary>
        public static bool ZoomAanchorWRadioButton_Locked {
            get {
                object obj = ResourceManager.GetObject("ZoomAanchorWRadioButton.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 False 的 System.Boolean 类型的本地化资源。
        /// </summary>
        public static bool ZoomAnchorLabel_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("ZoomAnchorLabel.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 True 的 System.Boolean 类型的本地化资源。
        /// </summary>
        public static bool ZoomAnchorLabel_Locked {
            get {
                object obj = ResourceManager.GetObject("ZoomAnchorLabel.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 True 的 System.Boolean 类型的本地化资源。
        /// </summary>
        public static bool ZoomAnchorPanel_Locked {
            get {
                object obj = ResourceManager.GetObject("ZoomAnchorPanel.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 False 的 System.Boolean 类型的本地化资源。
        /// </summary>
        public static bool ZoomFactorLabel_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("ZoomFactorLabel.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 True 的 System.Boolean 类型的本地化资源。
        /// </summary>
        public static bool ZoomFactorLabel_Locked {
            get {
                object obj = ResourceManager.GetObject("ZoomFactorLabel.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 False 的 System.Boolean 类型的本地化资源。
        /// </summary>
        public static bool ZoomSettingsPanel_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("ZoomSettingsPanel.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 True 的 System.Boolean 类型的本地化资源。
        /// </summary>
        public static bool ZoomSettingsPanel_Locked {
            get {
                object obj = ResourceManager.GetObject("ZoomSettingsPanel.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 True 的 System.Boolean 类型的本地化资源。
        /// </summary>
        public static bool ZoomTabPage_Locked {
            get {
                object obj = ResourceManager.GetObject("ZoomTabPage.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
    }
}
